name: Rust

on:
  push:
    branches: ["master", "riir"]
  pull_request:
    branches: ["master"]

jobs:
  rust:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest] # , windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ConorMacBride/install-package@v1
        with:
          # aclocal is in homebrew automake
          brew: automake
          # brew-cask: TODO
          apt: python3-dev libiberty-dev clang libavahi-client-dev
          # choco: TODO
      - run: python3 -m pip install --upgrade setuptools
      # need 1.77 beta for c"strings"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: beta
          components: clippy, rustfmt
      - run: cargo +beta test
      - run: cargo +beta clippy
      - run: cargo +beta fmt --check
      - name: Python tests
        run: env PATH=$(pwd)/target/debug:$PATH python ./test/testdistcc.py
        # This is the core of `make check` for the C implementation.
        # Some Python tests don't pass yet with the Rust build
        continue-on-error: true
      # TODO: Maybe also run C tests?

    #   - run: ./autogen.sh
    #   - run: ./configure
    # if: ${{ startsWith(matrix.os, 'ubuntu') }}
    #   - run: ./configure --without-libiberty
    # if: ${{ startsWith(matrix.os, 'macOS') }}
    #   - run: make
    #   - run: make check
#
